### ISSUE TITLE
I really need to recover my seed...

### ISSUE THREAD

**Issue by mbalance** [oed/seedsplit#11]
Guys, please help me out here, I'm having an issue installing https://github.com/oed/seedsplit on both Ubuntu 16 and now Windows 10. I have the "npm" logs here and will pay a good tip for a solution!

[2019-05-22T09_36_29_967Z-debug.log](https://github.com/oed/seedsplit/files/3209949/2019-05-22T09_36_29_967Z-debug.log)
[2019-05-22T09_38_50_792Z-debug.log](https://github.com/oed/seedsplit/files/3209950/2019-05-22T09_38_50_792Z-debug.log)
[2019-05-22T23_19_06_419Z-debug.log](https://github.com/oed/seedsplit/files/3209951/2019-05-22T23_19_06_419Z-debug.log)

**Comment by mbalance** [comment]
I followed https://blog.risingstack.com/node-js-windows-10-tutorial/ for installing Node.js and went with the Python 2.7.16 version.

**Comment by freeAgent85** [comment]
Have you tried using the binaries from the builds folder? https://github.com/oed/seedsplit/tree/master/builds

**Comment by mbalance** [comment]
@freeAgent85 No, I was using seedsplit-0.1.2 back in 2017. How would I use the binaries on Windows 10?

**Comment by freeAgent85** [comment]
Download the Windows binary, then fire up a Command Prompt window, navigate to the directory, and call it ("cli-win.exe").  It should tell you how to use it if you don't give it any parameters.

**Comment by freeAgent85** [comment]
I should add that this certainly involves a pretty high level of trust in the downloads/binaries and you should run it offline, etc.

**Comment by mbalance** [comment]
Thank you. I'm not getting the correct seed when I combine my shards though. It does say it's on version 0.1.2 when I type `cli-win.exe -V`

**Comment by mbalance** [comment]
> Releases 0.1.2 and older used a different Shamirs Secret Sharing library and are incompatible with newer versions. If you need to combine shards created with an old version, please use version 0.1.2.
The Shamirs Secret Sharing library in these builds seems to be the new one.

**Comment by mbalance** [comment]
Also when I try to run it through npm, Shamirs Secret Sharing is causing the error somehow it seems.

**Comment by mbalance** [comment]
Now most things work, but I'm getting this error
``throw err;
            ^

Error: Invalid entropy
    at Object.mnemonicToEntropy (/home/sam/.nvm/versions/node/v10.15.3/lib/node_modules/seedsplit/node_modules/bip39/index.js:106:39)
    at shardMnemonics.map.sm (/home/sam/.nvm/versions/node/v10.15.3/lib/node_modules/seedsplit/lib/seedsplit.js:25:13)
    at Array.map (<anonymous>)
    at Object.combine (/home/sam/.nvm/versions/node/v10.15.3/lib/node_modules/seedsplit/lib/seedsplit.js:23:31)
    at mnemonics (/home/sam/.nvm/versions/node/v10.15.3/lib/node_modules/seedsplit/bin/cli.js:40:34)
    at getMnemonics (/home/sam/.nvm/versions/node/v10.15.3/lib/node_modules/seedsplit/bin/cli.js:47:5)
    at result (/home/sam/.nvm/versions/node/v10.15.3/lib/node_modules/seedsplit/bin/cli.js:51:7)
    at prompt.get (/home/sam/.nvm/versions/node/v10.15.3/lib/node_modules/seedsplit/bin/cli.js:60:7)
    at /home/sam/.nvm/versions/node/v10.15.3/lib/node_modules/seedsplit/node_modules/prompt/lib/prompt.js:336:32
    at /home/sam/.nvm/versions/node/v10.15.3/lib/node_modules/seedsplit/node_modules/async/lib/async.js:154:25
``

**Comment by Shulyaka** [comment]
Hi,

You have to use an old version of seedsplit (0.1.2) with an old version of bip39 (2.3.0).
Please see issue #5 for some more details.
