### ISSUE TITLE
24 word seed produces error

### ISSUE THREAD

**Issue by brianmaas** [oed/seedsplit#3]
I have tried a bunch of different length seeds. The ones between 12 and 21 words work fine. I used this site to generate them: https://iancoleman.github.io/bip39/

When I use a 24 word seed it throws an error.

```
ubuntu@ubuntu:~$ seedsplit split -t 2 -s 3
Enter seed mnemonic:  
readline.js:1015
            throw err;
            ^

TypeError: Invalid entropy
    at Object.entropyToMnemonic (/usr/lib/node_modules/seedsplit/node_modules/bip39/index.js:95:37)
    at shards.map.shard (/usr/lib/node_modules/seedsplit/lib/seedsplit.js:16:18)
    at Array.map (native)
    at Object.split (/usr/lib/node_modules/seedsplit/lib/seedsplit.js:14:31)
    at result (/usr/lib/node_modules/seedsplit/bin/cli.js:29:36)
    at prompt.get (/usr/lib/node_modules/seedsplit/bin/cli.js:60:7)
    at /usr/lib/node_modules/seedsplit/node_modules/prompt/lib/prompt.js:336:32
    at /usr/lib/node_modules/seedsplit/node_modules/async/lib/async.js:154:25
    at assembler (/usr/lib/node_modules/seedsplit/node_modules/prompt/lib/prompt.js:333:9)
    at /usr/lib/node_modules/seedsplit/node_modules/prompt/lib/prompt.js:342:32
```
I've tried this on two different installs.

**Comment by vm81** [comment]
I didn't have any issues with 24 words on both Windows and Linex machines.  Maybe try to use the binaries in the 'Builds' folder?

**Comment by oed** [comment]
Hey, I'm using this upstream lib to deal with bip39 seeds: https://github.com/bitcoinjs/bip39
Could the issue possibly come from there?
Could you try the same seed with that lib?

**Comment by brianmaas** [comment]
I tried the windows and linux binaries and they both did work with the seed. I must have something misconfigured with node.
