### ISSUE TITLE
Can't get it to work after multiple reinstall's

### ISSUE THREAD

**Issue by mbalance** [oed/seedsplit#4]
I have nodejs and npm installed on my ubuntu 16.04 LTS, can anyone tell me what this error means?

/usr/local/lib/node_modules/seedsplit/bin/cli.js:23
function split({ threshold, shards }) {
               ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by mbalance** [comment]
`sudo npm cache clean -f
sudo npm install -g n
sudo n stable`

solved it

**Comment by oed** [comment]
So you had an old npm version?
Glad you managed to solve it :)

**Comment by mbalance** [comment]
Now getting this error on using `combine -t` and `split -t 2 -s 3` for 24 word phrase.

```readline.js:1021
            throw err;
            ^

Error: Error: canceled
    at prompt.get (/usr/local/lib/node_modules/seedsplit/bin/cli.js:59:22)
    at /usr/local/lib/node_modules/seedsplit/node_modules/prompt/lib/prompt.js:336:20
    at /usr/local/lib/node_modules/seedsplit/node_modules/async/lib/async.js:148:21
    at assembler (/usr/local/lib/node_modules/seedsplit/node_modules/prompt/lib/prompt.js:302:18)
    at /usr/local/lib/node_modules/seedsplit/node_modules/prompt/lib/prompt.js:342:20
    at /usr/local/lib/node_modules/seedsplit/node_modules/prompt/lib/prompt.js:542:14
    at onError (/usr/local/lib/node_modules/seedsplit/node_modules/read/lib/read.js:94:12)
    at Interface.<anonymous> (/usr/local/lib/node_modules/seedsplit/node_modules/read/lib/read.js:66:5)
    at emitNone (events.js:105:13)
    at Interface.emit (events.js:207:7)```

Seed is correct I have checked on myetherwallet site. Also I tried a 12 word from my Jaxx wallet and it worked, any thoughts?

**Comment by mbalance** [comment]
This is the error for `combine -t`

```throw err;
            ^

Error: Invalid entropy
    at Object.mnemonicToEntropy (/usr/local/lib/node_modules/seedsplit/node_modules/bip39/index.js:82:39)
    at shardMnemonics.map.sm (/usr/local/lib/node_modules/seedsplit/lib/seedsplit.js:25:13)
    at Array.map (<anonymous>)
    at Object.combine (/usr/local/lib/node_modules/seedsplit/lib/seedsplit.js:23:31)
    at mnemonics (/usr/local/lib/node_modules/seedsplit/bin/cli.js:40:34)
    at getMnemonics (/usr/local/lib/node_modules/seedsplit/bin/cli.js:47:5)
    at result (/usr/local/lib/node_modules/seedsplit/bin/cli.js:51:7)
    at prompt.get (/usr/local/lib/node_modules/seedsplit/bin/cli.js:60:7)
    at /usr/local/lib/node_modules/seedsplit/node_modules/prompt/lib/prompt.js:336:32
    at /usr/local/lib/node_modules/seedsplit/node_modules/async/lib/async.js:154:25```

**Comment by oed** [comment]
hm, seems like your seed is incompatible with the bip39 lib I'm using. 
If you want you can try to import your seed with the bip39 lib and see if it throws the same error: https://www.npmjs.com/package/bip39

**Comment by mbalance** [comment]
It was compatible a few months ago as I split it back then with this script and also tested combining them, everything was fine until today with my new laptop.

**Comment by oed** [comment]
So are you trying to combine shards or split a seed?

**Comment by mbalance** [comment]
both, as i still kept the original seed

**Comment by oed** [comment]
Ok, what service did you use to get your seed?
Also can you try using the binary from the `build` folder and see if there is any difference?

**Comment by mbalance** [comment]
It's a 'Ledger Nano S' 24 word seed.

**Comment by mbalance** [comment]
How would I do that?

**Comment by mbalance** [comment]
It worked!

**Comment by oed** [comment]
With the binary version? 
Must be something up with the dependancies then :/

**Comment by mbalance** [comment]
What happened here, why is seedsplit not working?

**Comment by mbalance** [comment]
Yes!

**Comment by oed** [comment]
I'm not sure what happend exactly. My guess would be that some change has happened to an dependancy that breaks things somehow.
Need to look further into this.

**Comment by mbalance** [comment]
By the way, if this repository every disappears, how would I recover my seed?

**Comment by mbalance** [comment]
Maybe I messed up the installation or something this time, IDK...

**Comment by oed** [comment]
Make sure to have a backup of this repo, or atleast the binary build.
I don't intend on removing it, but I can't guarantee github will keep it forever.

**Comment by mbalance** [comment]
Ok, thanks for your help!!

**Comment by mbalance** [comment]
You have a donation address?

**Comment by oed** [comment]
Not really, I'm just glad that you liked it :)

**Comment by mbalance** [comment]
Ok :)
